AWSTemplateFormatVersion: "2010-09-09"
Description: "Space Layer: Automation Services Discovery Policy"

Parameters:
  Environment:
    Type: String
    Description: "The environment name to prefix resource names."
    AllowedValues: [dev, stage, prod]

Resources:
  AutomationServicesDiscoveryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Environment}-AutomationServicesDiscovery"
      Description: !Sub "Allows ${Environment} read only access to specified automation services"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DiscoveryBase"
            Effect: "Allow"
            Action:
              # SSM
              - "ssm:DescribeParameters"
            Resource: "*"
      Roles:
        - !Sub "{{resolve:ssm:/iac/space/identity/${Environment}-dev-ops-engineer-human-role-name}}"

  # Parameter Store Exports
  AutomationServicesDiscoveryPolicyArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/iac/space/identity/${Environment}-automation-services-discovery-policy-arn"
      Description: "ARN for the AutomationServicesDiscoveryPolicy"
      Type: "String"
      Value: !GetAtt "AutomationServicesDiscoveryPolicy.PolicyArn"
